### ISSUE TITLE
Build issues with pch.h / Python.h

### ISSUE THREAD

**Issue by MORImementos** [Felk/dolphin#39] opened 2023-05-06 12:25 UTC
I have been working on trying to see if I can get the Python scripting added into project rio (dolphin fork for mario superstar baseball). After adding the changes, and trying to build, I kept getting two errors:

"cannot open include file: 'pch.h': no such file or directory" (in some cases this instead has said Python.h instead of pch.h)

And

"cannot read module dependencies file c:\Users\...\build\x64\release\scripting\registersmodule.h.module.json: Expecting element 'root' from namespace ".. Encountered 'None' with name " namespace ". The build order might be incorrect"

I am admittedly much less familiar with c++ in general, but I tried to clone this repo and build just to make sure it wasn't specific to Project Rio, and it still throws the same errors. Do you have any clue what it is that I could be doing that might be causing it? It seems like something with my configuration I guess, but I'm not certain

**Comment by Felk** [comment] 2023-05-11 19:15
Hey, thanks for reaching out.  
I think that's an issue I have already fixed locally. there was a ".h" reference somewhere where there should have been a "*.cpp" reference, or the other way around. Problem for the past couple of months is that I have had some local changes I wanted to push, but due to syncing with upstream some features broke and I couldn't motivate myself to re-implement them ever since.

**Comment by Felk** [comment] 2023-05-11 20:09
Maybe it's fixed after https://github.com/Felk/dolphin/commit/dc9dcfb6127ba50539226887b59ce0312c75f90f

Please try again with a clean rebuild

**Comment by thknkg** [comment] 2023-05-15 23:58
It does seem to build as intended now, thank you. Working on experimenting with it now to see what the capabilities it gives are. Thank you very much for your response. Do you have any future plans for the project?

**Comment by Felk** [comment] 2023-09-10 12:43
Forgot to close this as it's fixed.

> Do you have any future plans for the project?

Not anything in particular, just trying to maintain it and adding features as requested

**Closed by Felk** 2023-09-10 12:43 UTC
